# Generated by Django 3.1.3 on 2020-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(blank=True, choices=[('Heating', (('gas', 'Газ'), ('wood', 'Дърва'), ('central heating', 'Централно парно'))), ('Water', 'Вода'), ('Electricity', 'Ток')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
