# Generated by Django 3.1.3 on 2020-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20201122_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type_of_service',
            field=models.CharField(choices=[('Heating', (('gas', 'Газ'), ('wood', 'Дърва'), ('central heating', 'Централно парно'))), ('Water', 'Вода'), ('Electricity', 'Ток')], max_length=50),
        ),
    ]
